# Training hyperparameters
LEARNING_RATE = 0.003
LEARNING_RATE_DECAY = 0.8
BATCH_SIZE = 32
EPOCHS = 8

# Model hyperparameters
IMAGE_SIZE = 224
PATCH_SIZE = 14
NUM_PATCHES = IMAGE_SIZE**2 // PATCH_SIZE**2
EMBEDDING_DIM = 512
LATENT_DIM = 128
DECODER_ATTENTION_BLOCK_COUNT = 4
ATTENTION_HEAD_COUNT = 8
